apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

# Uncomment to add common labels
# commonLabels:
#   app: ecommerce
#   managed-by: kustomize

# Uncomment to add common annotations
# commonAnnotations:
#   deployed-by: kustomize
